### ISSUE TITLE
Varying resultant times between sunrise/sunset resources

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#16]
Given the same time and location, the USNO, Pyephem and SunriseSunset software do not align with their results.  It would be nice to provide a documented reason for the difference... or if there is a bug to have it fixed in the appropriate software (which may not reside in SunriseSunset).

Sunday UTC 6 September 2009     
for atlanta (33.8, -84.4)
more specifically (33.766667, -84.416667)

USNO (http://bit.ly/2iPNelk) - (33.766667, -84.416667)
Sunrise: 2009/9/6 11:15:00 UTC
Sunset:  2009/9/6 23:56:00 UTC 

Pyephem (http://rhodesmill.org/pyephem/rise-set.html) - (33.8, -84.4)
Sunrise: 2009/9/6 11:14:57 UTC
Sunset:  2009/9/6 23:56:10 UTC

SunriseSunset (33.766667, -84.416667)
Sunrise: 2009/9/6 11:16:33 UTC
Sunset: 2009/9/6 23:58:17 UTC

http://api.sunrise-sunset.org/ (http://api.sunrise-sunset.org/json?lat=33.766667&lng=-84.416667&date=2009-09-06)
SunriseSunset (33.766667, -84.416667)
Sunrise: 2009/9/6 11:15:27 UTC
Sunset:  2009/9/6 23:55:58 UTC

**Comment by caarmen** [comment]
I may add to the list, the sunrisesunset.com website (not at all related to this project), which reports:
Sunrise: 7:15
Sunset  19:58


Since different sources may have slight calculation differences (maybe due to when rounding is performed, for example), SunriseSunset unit tests allow some difference between other sources.  By default the unit tests accept a difference of up to 2.25 minutes (135 seconds).  

The Pyephem and sunrisesunset.com calculations are within this limit.

The USNO sunset time is off by 137 seconds, just 2 seconds more than the default allowance of 135 seconds.  However, since USNO doesn't appear to have seconds at all, maybe that is why. 

I've added a unit test for Atlanta, comparing to these three sources (USNO, Pyephem, and sunrisesunset.com)
