### ISSUE TITLE
Minor Utility Class Improvements

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#26]
After reading this thread: http://stackoverflow.com/questions/25223553/how-can-i-create-an-utility-class, I noticed a couple of minor improvements that can be refactored into the SunriseSunset class.

 "For a completely stateless utility class in Java I suggest the class be declared public and final and have a private constructor to prevent instantiation. "

`public final class SunriseSunset {  // added final keyword`

"Methods only used by the class itself should be private."

These are not methods, but should they be private? I don't know any reason why the user would need to use these...

```
public static final double SUN_ALTITUDE_SUNRISE_SUNSET = -0.833;
public static final double SUN_ALTITUDE_CIVIL_TWILIGHT = -6.0;
public static final double SUN_ALTITUDE_NAUTICAL_TWILIGHT = -12.0;
public static final double SUN_ALTITUDE_ASTRONOMICAL_TWILIGHT = -18.0;

```

Also are the Gregorian and Julian methods supposed to be public or internal only?  If internal, they should be private.

**Comment by caarmen** [comment]
Indeed the class can be final.  It already has the private constructor.  I just added the final keyword.

I prefer to keep those constants and the gregorian and julien methods public.  I thought they might be useful.  The methods for sure can't be private because they are tested by unit tests.  They could have package-level visibility, but I prefer to keep them public.

**Comment by robertjliguori** [comment]
Thanks for the update!  Btw, here is my post with initramfs's suggestions: http://robertjliguori.blogspot.com/2017/01/java-utility-classes-quicklook.html
