### ISSUE TITLE
Add package.html files to support Javadoc

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#9]
Add package.html files to support Javadoc

**Comment by caarmen** [comment]
Added `package-info.java` instead of `package.html`, as this is generally preferred: http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#packagecomment

It looks a bit like overkill though. I only have a single java file in this package...  There's a bit of redundancy in the main `package-summary.html` file because of this.

**Comment by robertjliguori** [comment]
Okay.  Thanks for adding this.
